export const cities = [
  {
    label: "Toshkent",
    value: "toshkent",
    latitude: 41.2995,
    longitude: 69.2401,
    regions: [
      {
        label: "Toshkent shahar",
        value: "toshkent_city",
        latitude: 41.2995,
        longitude: 69.2401,
      },
      { label: "Bekobod", value: "bekobod" },
      { label: "Buka", value: "buka" },
      { label: "Chirchiq", value: "chirchiq" },
      { label: "Ohangaron", value: "ohangaron" },
      { label: "Parkent", value: "parkent" },
      { label: "Pskent", value: "pskent" },
      { label: "Quyichirchiq", value: "quyichirchiq" },
      { label: "Salor", value: "salor" },
      { label: "Tuytepa", value: "tuytepa" },
      { label: "Yangiobod", value: "yangiobod" },
      { label: "Yuqorichirchiq", value: "yuqorichirchiq" },
      { label: "Zangiota", value: "zangiota" },
      { label: "Zafar", value: "zafar" },
    ],
  },
  {
    label: "Andijon",
    value: "andijon",
    latitude: 40.7816,
    longitude: 72.3452,
    regions: [
      { label: "Andijon shahar", value: "andijon_city" },
      { label: "Asaka", value: "asaka" },
      { label: "Baliqchi", value: "baliqchi" },
      { label: "Bo'z", value: "boz" },
      { label: "Buloqboshi", value: "buloqboshi" },
      { label: "Izboskan", value: "izboskan" },
      { label: "Jalaquduq", value: "jalaquduq" },
      { label: "Marhamat", value: "marhamat" },
      { label: "Oltinko'l", value: "oltinkol" },
      { label: "Paxtaobod", value: "paxtaobod" },
      { label: "Shahrixon", value: "shahrixon" },
      { label: "Ulug'nor", value: "ulugnor" },
      { label: "Xonobod", value: "xonobod" },
    ],
  },
  {
    label: "Buxoro",
    value: "buxoro",
    latitude: 40.7816,
    longitude: 72.3452,
    regions: [
      { label: "Buxoro shahar", value: "buxoro_city" },
      { label: "Alat", value: "alat" },
      { label: "Buxoro", value: "buxoro" },
      { label: "G'ijduvon", value: "gijduvon" },
      { label: "Jondor", value: "jondor" },
      { label: "Kogon", value: "kogon" },
      { label: "Olot", value: "olot" },
      { label: "Peshku", value: "peshku" },
      { label: "Qorako'l", value: "qorakol" },
      { label: "Romitan", value: "romitan" },
      { label: "Shofirkon", value: "shofirkon" },
      { label: "Vobkent", value: "vobkent" },
      { label: "Yangiobod", value: "yangiobod" },
    ],
  },
  {
    label: "Farg'ona",
    value: "fargona",
    latitude: 40.3890,
    longitude: 71.7874,
    regions: [
      { label: "Farg'ona shahar", value: "fargona_city" },
      { label: "Bag'dod", value: "bag'dod" },
      { label: "Beshariq", value: "beshariq" },
      { label: "Buvayda", value: "buvayda" },
      { label: "Dang'ara", value: "dang'ara" },
      { label: "Farg'ona", value: "fargona" },
      { label: "Furqat", value: "furqat" },
      { label: "Oltiariq", value: "oltiariq" },
      { label: "O'zbekiston", value: "o'zbekiston" },
      { label: "Quva", value: "quva" },
      { label: "Rishton", value: "rishton" },
      { label: "So'x", value: "so'x" },
      { label: "Toshloq", value: "toshloq" },
      { label: "Uchko'prik", value: "uchko'prik" },
      { label: "Yozyovon", value: "yozyovon" },
    ],
  },
  {
    label: "Jizzax",
    value: "jizzax",
    latitude: 40.1156,
    longitude: 67.8424,
    regions: [
      { label: "Jizzax shahar", value: "jizzax_city" },
      { label: "Arnasoy", value: "arnasoy" },
      { label: "Baxmal", value: "baxmal" },
      { label: "Forish", value: "forish" },
      { label: "G'allaorol", value: "g'allaorol" },
      { label: "G'azalkent", value: "g'azalkent" },
      { label: "Mirzachul", value: "mirzachul" },
      { label: "Paxtakor", value: "paxtakor" },
      { label: "Yangiabad", value: "yangiabad" },
      { label: "Yangirabot", value: "yangirabot" },
      { label: "Zomin", value: "zomin" },
    ],
  },
  {
    label: "Xorazm",
    value: "xorazm",
    latitude: 41.3755,
    longitude: 60.3590,
    regions: [
      { label: "Urganch shahar", value: "urganch_city" },
      { label: "Bag'at", value: "bag'at" },
      { label: "Bog'ot", value: "bog'ot" },
      { label: "Gurlan", value: "gurlan" },
      { label: "Hazorasp", value: "hazorasp" },
      { label: "Khiva", value: "khiva" },
      { label: "Qo'ng'irot", value: "qong'irot" },
      { label: "Shovot", value: "shovot" },
      { label: "Urganch", value: "urganch" },
      { label: "Xonqa", value: "xonqa" },
    ],
  },
  {
    label: "Namangan",
    value: "namangan",
    latitude: 40.9986,
    longitude: 71.6722,
    regions: [
      { label: "Namangan shahar", value: "namangan_city" },
      { label: "Chortoq", value: "chortoq" },
      { label: "Kosonsoy", value: "kosonsoy" },
      { label: "Namangan", value: "namangan" },
      { label: "Pap", value: "pap" },
      { label: "To'rakul", value: "to'rakul" },
      { label: "Uychi", value: "uychi" },
      { label: "Yangiqo'rg'on", value: "yangiqo'rg'on" },
    ],
  },
  {
    label: "Navoiy",
    value: "navoiy",
    latitude: 40.0842,
    longitude: 65.3798,
    regions: [
      { label: "Navoiy shahar", value: "navoiy_city" },
      { label: "Kyzyltepa", value: "kyzyltepa" },
      { label: "Navbakhor", value: "navbakhor" },
      { label: "Nurota", value: "nurota" },
      { label: "Qiziltepa", value: "qiziltepa" },
      { label: "Tomdi", value: "tomdi" },
      { label: "Uchquduq", value: "uchquduq" },
      { label: "Xatirchi", value: "xatirchi" },
      { label: "Zarafshon", value: "zarafshon" },
    ],
  },
  {
    label: "Qashqadaryo",
    value: "qashqadaryo",
    latitude: 38.5225,
    longitude: 66.7650,
    regions: [
      { label: "Qarshi shahar", value: "qarshi_city" },
      { label: "Chirakchi", value: "chirakchi" },
      { label: "Dehkanobod", value: "dehkanobod" },
      { label: "Kamashi", value: "kamashi" },
      { label: "Kasbi", value: "kasbi" },
      { label: "Kitob", value: "kitob" },
      { label: "Koson", value: "koson" },
      { label: "Mirishkor", value: "mirishkor" },
      { label: "Muborak", value: "muborak" },
      { label: "Nishon", value: "nishon" },
      { label: "Qamashi", value: "qamashi" },
      { label: "Shahrisabz", value: "shahrisabz" },
      { label: "Yakkabog'", value: "yakkabog'" },
    ],
  },
  {
    label: "Qoraqalpog'iston Respublikasi",
    value: "qoraqalpog'iston",
    regions: [
      { label: "Nukus shahar", value: "nukus_city" },
      { label: "Bag'at", value: "bag'at" },
      { label: "Beruniy", value: "beruniy" },
      { label: "Chimboy", value: "chimboy" },
      { label: "Hazorasp", value: "hazorasp" },
      { label: "Kegeyli", value: "kegeyli" },
      { label: "Qo'ng'irot", value: "qong'irot" },
      { label: "Shumanay", value: "shumanay" },
      { label: "Taxta Ko'pir", value: "taxta_ko'pir" },
      { label: "To'rtku'l", value: "to'rtku'l" },
      { label: "Xo'jayli", value: "xo'jayli" },
    ],
  },
  {
    label: "Samarqand",
    value: "samarqand",
    latitude: 39.6270,
    longitude: 66.9749,
    regions: [
      { label: "Samarqand shahar", value: "samarqand_city" },
      { label: "Bulung'ur", value: "bulung'ur" },
      { label: "Ishtixon", value: "ishtixon" },
      { label: "Jomboy", value: "jomboy" },
      { label: "Kattaqo'rg'on", value: "kattaqo'rg'on" },
      { label: "Narpay", value: "narpay" },
      { label: "Nurobod", value: "nurobod" },
      { label: "Oqdaryo", value: "oqdaryo" },
      { label: "Paxtachi", value: "paxtachi" },
      { label: "Payariq", value: "payariq" },
      { label: "Pastdarg'om", value: "pastdarg'om" },
      { label: "Samarqand", value: "samarqand" },
      { label: "Toyloq", value: "toyloq" },
      { label: "Urgut", value: "urgut" },
    ],
  },
  {
    label: "Surxondaryo",
    value: "surxondaryo",
    latitude: 37.1695,
    longitude: 67.7802,
    regions: [
      { label: "Termiz shahar", value: "termiz_city" },
      { label: "Angor", value: "angor" },
      { label: "Boysun", value: "boysun" },
      { label: "Denov", value: "denov" },
      { label: "Jarkurgan", value: "jarkurgan" },
      { label: "Kizirik", value: "kizirik" },
      { label: "Kumkurghon", value: "kumkurghon" },
      { label: "Muzrabot", value: "muzrabot" },
      { label: "Oltinsoy", value: "oltinsoy" },
      { label: "Sariosiyo", value: "sariosiyo" },
      { label: "Shirabad", value: "shirabad" },
      { label: "Termiz", value: "termiz" },
      { label: "Uzun", value: "uzun" },
      { label: "Yakkabog'", value: "yakkabog'" },
    ],
  },
  {
    label: "Toshkent viloyati",
    value: "toshkent_viloyati",
    regions: [
      { label: "Bekobod", value: "bekobod" },
      { label: "Buka", value: "buka" },
      { label: "Chinoz", value: "chinoz" },
      { label: "Chirchiq", value: "chirchiq" },
      { label: "Olmaliq", value: "olmaliq" },
      { label: "Oqtosh", value: "oqtosh" },
      { label: "Parkent", value: "parkent" },
      { label: "Pskent", value: "pskent" },
      { label: "Quyichirchiq", value: "quyichirchiq" },
      { label: "To'rtku'l", value: "to'rtku'l" },
      { label: "Yangiyo'l", value: "yangiyo'l" },
      { label: "Zangiota", value: "zangiota" },
      { label: "Zarbdor", value: "zarbdor" },
    ],
  },
];

// export const cities2 = [
//   {
//     "label": "Toshkent",
//     "value": "toshkent",
//     "latitude": 41.2995,
//     "longitude": 69.2401,
//     "regions": [
//       {
//         "label": "Toshkent shahar",
//         "value": "toshkent_city",
//         "latitude": 41.2995,
//         "longitude": 69.2401,
//         "places": [
//           {
//             "label": "Place 1",
//             "value": "place_1",
//             "latitude": 41.2995,
//             "longitude": 69.2401
//           }
//         ]
//       }
//     ]
//   },
//   {
//     "label": "Andijon",
//     "value": "andijon",
//     "latitude": 40.7816,
//     "longitude": 72.3452,
//     "regions": []
//   },
//   {
//     "label": "Buxoro",
//     "value": "buxoro",
//     "latitude": 40.7816,
//     "longitude": 72.3452,
//     "regions": []
//   },
//   {
//     "label": "Farg'ona",
//     "value": "fargona",
//     "latitude": 40.3890,
//     "longitude": 71.7874,
//     "regions": []
//   },
//   {
//     "label": "Jizzax",
//     "value": "jizzax",
//     "latitude": 40.1156,
//     "longitude": 67.8424,
//     "regions": []
//   },
//   {
//     "label": "Namangan",
//     "value": "namangan",
//     "latitude": 40.9986,
//     "longitude": 71.6722,
//     "regions": []
//   },
//   {
//     "label": "Navoiy",
//     "value": "navoiy",
//     "latitude": 40.0842,
//     "longitude": 65.3798,
//     "regions": []
//   },
//   {
//     "label": "Qashqadaryo",
//     "value": "qashqadaryo",
//     "latitude": 38.5225,
//     "longitude": 66.7650,
//     "regions": []
//   },
//   {
//     "label": "Samarqand",
//     "value": "samarqand",
//     "latitude": 39.6270,
//     "longitude": 66.9749,
//     "regions": []
//   },
//   {
//     "label": "Sirdaryo",
//     "value": "sirdaryo",
//     "latitude": 40.5158,
//     "longitude": 68.7790,
//     "regions": []
//   },
//   {
//     "label": "Surxondaryo",
//     "value": "surxondaryo",
//     "latitude": 37.1695,
//     "longitude": 67.7802,
//     "regions": []
//   },
//   {
//     "label": "Xorazm",
//     "value": "xorazm",
//     "latitude": 41.3755,
//     "longitude": 60.3590,
//     "regions": []
//   }
// ]
